# https://taskfile.dev
version: '3'

tasks:
  build:
    - test {{.CLI_ARGS}}
    - tinygo version
    - >
      tinygo build
      -target ./target.json
      -gc     leaking
      -o      cart.wasm
      {{.CLI_ARGS}}
    # remove debug info but only if wabt is installed
    - wasm-strip cart.wasm || true
  run:
    - task: build
    - w4 run-native ./cart.wasm
